name: flip7-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
    - torch>=2.1.0
    - numpy>=1.24
    - tqdm>=4.65
    - seaborn>=0.12
    - matplotlib>=3.6
    - jupyter>=1.0
# If you want CUDA support, create the env and then install a CUDA-enabled torch build per https://pytorch.org

